### PR TITLE
Add support for the AIX Big archive format

### LINKED ISSUE #1: Support AIX big archive variant
This is now supported by the latest LLVM version, so it shouldn't be too hard to add.

### PR DESCRIPTION
**Pull request by bjorn3**
I haven't tested this code as I don't have a mainframe running AIX.

cc @ecnelises for https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/New.20Tier-3.20target.20proposal.3A.20powerpc64-ibm.E2.80.A6.20compiler-team.23553

Fixes #1

### CODE REVIEW

**Comment by bjorn3** [comment]
Just verified this doesn't regress anything on Linux by applying

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 5fddb408f8e..f66b4612c25 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -110,8 +110,7 @@ checksum = "c794e162a5eff65c72ef524dfe393eb923c354e350bb78b9c7383df13f3bc142"
 [[package]]
 name = "ar_archive_writer"
 version = "0.1.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "16f8a694a78724bb6f745ca5b987eada762c2b17c08d8344a20c633fb5d0f0fb"
+source = "git+https://github.com/rust-lang/ar_archive_writer?branch=aix_big#563333a1da68421b2fea1fb035da08feab628abe"
 dependencies = [
  "object 0.29.0",
 ]
diff --git a/compiler/rustc_codegen_ssa/Cargo.toml b/compiler/rustc_codegen_ssa/Cargo.toml
index a70650ab1c3..e5b0cee48c4 100644
--- a/compiler/rustc_codegen_ssa/Cargo.toml
+++ b/compiler/rustc_codegen_ssa/Cargo.toml
@@ -7,7 +7,7 @@ edition = "2021"
 test = false
 
 [dependencies]
-ar_archive_writer = "0.1.0"
+ar_archive_writer = { git = "https://github.com/rust-lang/ar_archive_writer", branch = "aix_big" }
 bitflags = "1.2.1"
 cc = "1.0.69"
 itertools = "0.10.1"
diff --git a/src/tools/tidy/src/extdeps.rs b/src/tools/tidy/src/extdeps.rs
index aad57cacbb4..de9c4241c3b 100644
--- a/src/tools/tidy/src/extdeps.rs
+++ b/src/tools/tidy/src/extdeps.rs
@@ -4,7 +4,10 @@
 use std::path::Path;
 
 /// List of allowed sources for packages.
-const ALLOWED_SOURCES: &[&str] = &["\"registry+https://github.com/rust-lang/crates.io-index\""];
+const ALLOWED_SOURCES: &[&str] = &[
+    "\"registry+https://github.com/rust-lang/crates.io-index\"",
+    "\"git+https://github.com/rust-lang/ar_archive_writer?branch=aix_big#563333a1da68421b2fea1fb035da08feab628abe\"",
+];
 
 /// Checks for external package sources. `root` is the path to the directory that contains the
 /// workspace `Cargo.toml`.
```

on top of https://github.com/rust-lang/rust/pull/97485.

**Comment by ecnelises** [comment]
Did a quick test on AIX using following code:

```rust
use std::fs::File;
use std::io::Read;
use ar_archive_writer::{write_archive_to_stream, ArchiveKind, NewArchiveMember};

fn main() {
    let mut file = File::create("tmp.a").unwrap();
    let mut first = Vec::new();
    let mut second = Vec::new();
    let mut first_file = File::open("first.o").expect("");
    let mut second_file = File::open("second.o").expect("");
    let _ = first_file.read_to_end(&mut first);
    let _ = second_file.read_to_end(&mut second);
    let _ = write_archive_to_stream(&mut file, &[
        NewArchiveMember {
            buf: Box::new(first),
            get_symbols: |_, _| Ok(false),
            member_name: String::from("first.o"),
            mtime: 0,
            uid: 500,
            gid: 1,
            perms: 0o644,
        },
        NewArchiveMember {
            buf: Box::new(second),
            get_symbols: |_, _| Ok(false),
            member_name: String::from("second.o"),
            mtime: 0,
            uid: 500,
            gid: 1,
            perms: 0o644,
        },
    ], true, ArchiveKind::AixBig, true, false);
}
```

However `ar t tmp.a` doesn't work as expected:

```
first.o
.
first.o
.
first.o
.
first.o
.
... (infinite loop)
```

I'm looking into it.

**Comment by bjorn3** [comment]
There seem to be two divergences with LLVM. The first is because I had to use `{:<12o}` instead of `{:12o}`. Currently investigating the other one.

**Comment by bjorn3** [comment]
Fixed both issues. This now results in identical archives as llvm-ar for empty object files.

**Comment by bjorn3** [comment]
Found another divergence when using actual object files.

**Comment by bjorn3** [comment]
Never mind. That was caused by using a dummy `get_symbols` instead of `get_native_object_symbols`.

**Comment by bjorn3** [comment]
I'm now fairly confident that this PR is correct.

**Comment by bjorn3** [comment]
Released as v0.1.1.

**Comment by ecnelises** [comment]
`master` works, thanks!

**Comment by bjorn3** [comment]
I've updated https://github.com/rust-lang/rust/pull/97485 with the new version of ar_archive_writer, but I haven't yet wired up aix big support. It should be a matter of adding a single arm to the match on `sess.target.archive_format` in compiler/rustc_codegen_ssa/src/back/archive.rs though. I prefer leaving it to the PR adding an AIX target to rustc though to keep the PR functionally identical to what we currently have.

**Pull request merged**
